version: 0.0
os: linux

files:
  - source: spring-boot-web-thymeleaf-1.0.war
    destination: /opt/tomcat/webapps/

hooks:
  BeforeInstall:
    - loaction: scripts/before.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: scripts/after.sh
      timeout: 60
      runas: root


