version: 0.0

files:
  - source: /target/*.war
    destination: /var/www/html/

hooks:
  BeforeInstall:
    loaction: scripts/before.sh
    timeout: 300
    runas: root

  AfterInstall:
    location: scripts/after.sh
    timeout: 300
    runas: root


