version: 0.0

files:
  - source: target/*.war
    destination: /opt/tomcat/webapps/

hooks:
  BeforeInstall:
    loaction: scripts/before.sh
    timeout: 300
    runas: root

  AfterInstall:
    location: scripts/after.sh
    timeout: 300
    runas: root


