version: 0.2

phases: 
  install:
    runtime-version:
      java: corretto11
  build:
    commands:
      - mvn install

artifacts:
  files:
    - 'src/main/**/*'
    - 'target/**/*'
    - '.classpath/**/*'
    - '.project/**/*'
    - '.springBeans/**/*'
    - 'appspec.yml/**/*'

