version: 0.2
phases:
  install:
    runtime-version:
    java: corretto11
  build:
    commands:
      - echo Build started on `date`
      - mvn install
    
artifacts:
  files:
     - scr/main/**/*
     - target/**/*
     - scripts/**/*
     - appspec.yml
    
