version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - mvn install 

artifacts:
  files:
    - 'src/main/**/*'
    - 'target/**/*'
    - '.classpath/**/*'
    - '.project/**/*'
    - '.springBeans/**/*'
    - 'appspec.yml/**/*'

