version: 0.2
phases:
  install:
    runtime-version:
    java: 12  
  build:
    commands:
      - echo Build started on `date`
      - mvn install
    
artifacts:
  files:
     - scr/main/**/*
     - target/**/*
    
